/**
 * Mock Claude API Response
 */

export const mockClaudeResponse = async (req) => {
    const body = await req.json();
    console.log('[Mock Claude] generating summary for prompt length:', body.messages[0].content.length);

    return new Response(JSON.stringify({
        id: "msg_mock123",
        type: "message",
        role: "assistant",
        content: [
            {
                type: "text",
                text: "This is a mock summary generated by the test stub. It represents a concise overview of the article content, ensuring that the summarization pipeline functions correctly without calling the external API."
            }
        ],
        model: "claude-3-haiku-20240307",
        stop_reason: "end_turn",
        usage: { input_tokens: 50, output_tokens: 30 }
    }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
    });
};
